// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultUsername():Promise<string>;

export function Hello():Promise<string>;

export function Verify(arg1:string):Promise<any>;
