// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultUsername() {
  return window['go']['main']['App']['DefaultUsername']();
}

export function Hello() {
  return window['go']['main']['App']['Hello']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}
